name: Update pre-commit
on:
  schedule:
    - cron: "0 0 * * 1" # 00:00 UTC every Monday
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pre-commit
        run: pip install --no-cache-dir pre-commit

      - name: Update pre-commit
        run: pre-commit autoupdate

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update .pre-commit-config.yaml"
